[ivr-fornecedor]
exten => s,1,NoOp(Fornecedor: ${CALLERID(num)})
 same => n,Answer()

 same => n,Playback(custom/bem_vindo_fornecedor)
 same => n,Background(custom/menu_fornecedor)
 same => n,WaitExten(8)

exten => 1,1,Goto(recebe-doc,s,1)
exten => 2,1,Goto(ivr-menugeral,s,1)

[recebe-doc]
exten => s,1,Set(LOOP=0)
 same => n(loop),Background(custom/digite_cpf_cnpj)
 same => n,WaitExten(8)

exten => _X.,1,Set(DOC=${EXTEN})
 same => n,Set(VALIDO=SIM)
 same => n,GotoIf($["${VALIDO}"="SIM"]?menu:retry)

 same => n(retry),Set(LOOP=$[${LOOP}+1])
 same => n,GotoIf($[${LOOP}<3]?loop:fim)

 same => n(menu),Goto(menu-fornecedor,s,1)
 same => n(fim),Hangup()

[menu-fornecedor]
exten => s,1,Background(custom/opcoes_fornecedor)
 same => n,WaitExten(8)
