[ivr-colaborador]
exten => s,1,NoOp(Colaborador: ${CALLERID(num)})
 same => n,Answer()

 same => n,Playback(custom/servico_exclusivo)
 same => n,Background(custom/menu_colaborador)
 same => n,WaitExten(8)

exten => 1,1,Goto(menu-saf,s,1)
exten => 2,1,Goto(menu-suporte,s,1)
exten => 3,1,Goto(menu-gbs,s,1)
exten => 0,1,Goto(ivr-menugeral,s,1)

[menu-saf]
exten => s,1,Background(custom/menu_saf)
 same => n,WaitExten(8)

[menu-suporte]
exten => s,1,Background(custom/menu_suporte)
 same => n,WaitExten(8)

[menu-gbs]
exten => s,1,Playback(custom/aguarde)
 same => n,Dial(SIP/fila/1111,120)
 same => n,Hangup()
